-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Policies for users
-- Allow anyone to insert (for registration)
CREATE POLICY "Allow public registration" ON users FOR INSERT WITH CHECK (true);
-- Allow users to view their own profile
CREATE POLICY "Users can view own profile" ON users FOR SELECT USING (true); -- Simplified for prototype, ideally check ID
-- Allow users to update their own profile
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (true); -- Simplified for prototype

-- Students (Siswa) Table
CREATE TABLE IF NOT EXISTS siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT UNIQUE NOT NULL,
    nama TEXT NOT NULL,
    kelas TEXT NOT NULL,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on siswa
ALTER TABLE siswa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own students" ON siswa FOR ALL USING (true); -- Simplified

-- Agenda Guru Table
CREATE TABLE IF NOT EXISTS agenda_guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT, -- Path to file in storage or local
    content TEXT, -- For manual entry
    uploaded_by UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on agenda_guru
ALTER TABLE agenda_guru ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own agenda" ON agenda_guru FOR ALL USING (true);

-- Laporan Piket Table
CREATE TABLE IF NOT EXISTS laporan_piket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on laporan_piket
ALTER TABLE laporan_piket ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own piket" ON laporan_piket FOR ALL USING (true);

-- Laporan Walikelas Table
CREATE TABLE IF NOT EXISTS laporan_walikelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on laporan_walikelas
ALTER TABLE laporan_walikelas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own walikelas" ON laporan_walikelas FOR ALL USING (true);

-- E-Raport Table
CREATE TABLE IF NOT EXISTS eraport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES siswa(nis),
    nilai INTEGER NOT NULL,
    semester TEXT NOT NULL,
    mapel TEXT NOT NULL,
    teacher_id UUID REFERENCES users(id),
    tugas1 INTEGER DEFAULT 0,
    tugas2 INTEGER DEFAULT 0,
    formatif1 INTEGER DEFAULT 0,
    formatif2 INTEGER DEFAULT 0,
    pts INTEGER DEFAULT 0,
    uas INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on eraport
ALTER TABLE eraport ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own eraport" ON eraport FOR ALL USING (true);

-- KKM Table
CREATE TABLE IF NOT EXISTS kkm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    value INTEGER NOT NULL,
    teacher_id UUID REFERENCES users(id),
    UNIQUE(subject, teacher_id)
);

-- Enable RLS on kkm
ALTER TABLE kkm ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own kkm" ON kkm FOR ALL USING (true);

-- Absensi Siswa Table
CREATE TABLE IF NOT EXISTS absensi_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES siswa(nis),
    tanggal DATE NOT NULL,
    status TEXT NOT NULL, -- Hadir, Izin, Sakit, Alpa
    teacher_id UUID REFERENCES users(id),
    UNIQUE(nis, tanggal, teacher_id)
);

-- Enable RLS on absensi_siswa
ALTER TABLE absensi_siswa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own absensi" ON absensi_siswa FOR ALL USING (true);

-- AI Documents Table
CREATE TABLE IF NOT EXISTS ai_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    pdf_url TEXT,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on ai_documents
ALTER TABLE ai_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own ai_docs" ON ai_documents FOR ALL USING (true);

-- STORAGE SETUP
-- Run these to enable storage for uploads
-- 1. Create the bucket (Safe to run multiple times)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('EduAdmin', 'EduAdmin', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Create policies for the bucket
-- Note: If you get "policy already exists" errors, you can ignore them or drop the policy first.

-- Policy to allow anyone to read public files
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' 
        AND schemaname = 'storage' 
        AND policyname = 'Public Access'
    ) THEN
        CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'EduAdmin');
    END IF;
END $$;

-- Policy to allow authenticated uploads
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' 
        AND schemaname = 'storage' 
        AND policyname = 'Allow Uploads'
    ) THEN
        CREATE POLICY "Allow Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'EduAdmin');
    END IF;
END $$;

-- Policy to allow updates
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' 
        AND schemaname = 'storage' 
        AND policyname = 'Allow Updates'
    ) THEN
        CREATE POLICY "Allow Updates" ON storage.objects FOR UPDATE USING (bucket_id = 'EduAdmin');
    END IF;
END $$;

-- Policy to allow deletes
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' 
        AND schemaname = 'storage' 
        AND policyname = 'Allow Deletes'
    ) THEN
        CREATE POLICY "Allow Deletes" ON storage.objects FOR DELETE USING (bucket_id = 'EduAdmin');
    END IF;
END $$;
