-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Students (Siswa) Table
CREATE TABLE IF NOT EXISTS siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT UNIQUE NOT NULL,
    nama TEXT NOT NULL,
    kelas TEXT NOT NULL,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Agenda Guru Table
CREATE TABLE IF NOT EXISTS agenda_guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT, -- Path to file in storage or local
    content TEXT, -- For manual entry
    uploaded_by UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Laporan Piket Table
CREATE TABLE IF NOT EXISTS laporan_piket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Laporan Walikelas Table
CREATE TABLE IF NOT EXISTS laporan_walikelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES users(id),
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- E-Raport Table
CREATE TABLE IF NOT EXISTS eraport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES siswa(nis),
    nilai INTEGER NOT NULL,
    semester TEXT NOT NULL,
    mapel TEXT NOT NULL,
    teacher_id UUID REFERENCES users(id),
    tugas1 INTEGER DEFAULT 0,
    tugas2 INTEGER DEFAULT 0,
    formatif1 INTEGER DEFAULT 0,
    formatif2 INTEGER DEFAULT 0,
    pts INTEGER DEFAULT 0,
    uas INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- KKM Table
CREATE TABLE IF NOT EXISTS kkm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    value INTEGER NOT NULL,
    teacher_id UUID REFERENCES users(id),
    UNIQUE(subject, teacher_id)
);

-- Absensi Siswa Table
CREATE TABLE IF NOT EXISTS absensi_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES siswa(nis),
    tanggal DATE NOT NULL,
    status TEXT NOT NULL, -- Hadir, Izin, Sakit, Alpa
    teacher_id UUID REFERENCES users(id),
    UNIQUE(nis, tanggal, teacher_id)
);

-- AI Documents Table
CREATE TABLE IF NOT EXISTS ai_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    pdf_url TEXT,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
