-- Users Table (Profile)
-- Note: This table stores additional user info. The primary auth is handled by Supabase Auth.
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies for users
CREATE POLICY "Users can view their own profile" ON public.users 
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.users 
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON public.users 
    FOR INSERT WITH CHECK (auth.uid() = id);

-- Students (Siswa) Table
CREATE TABLE IF NOT EXISTS public.siswa (
    nis TEXT PRIMARY KEY,
    nama TEXT NOT NULL,
    kelas TEXT NOT NULL,
    created_by UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on siswa
ALTER TABLE public.siswa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own students" ON public.siswa 
    FOR SELECT USING (auth.uid() = created_by);

CREATE POLICY "Users can insert their own students" ON public.siswa 
    FOR INSERT WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can update their own students" ON public.siswa 
    FOR UPDATE USING (auth.uid() = created_by);

CREATE POLICY "Users can delete their own students" ON public.siswa 
    FOR DELETE USING (auth.uid() = created_by);

-- Agenda Guru Table
CREATE TABLE IF NOT EXISTS public.agenda_guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    uploaded_by UUID REFERENCES auth.users NOT NULL,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on agenda_guru
ALTER TABLE public.agenda_guru ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own agenda" ON public.agenda_guru 
    FOR ALL USING (auth.uid() = uploaded_by);

-- Laporan Piket Table
CREATE TABLE IF NOT EXISTS public.laporan_piket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES auth.users NOT NULL,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on laporan_piket
ALTER TABLE public.laporan_piket ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own piket" ON public.laporan_piket 
    FOR ALL USING (auth.uid() = teacher_id);

-- Laporan Walikelas Table
CREATE TABLE IF NOT EXISTS public.laporan_walikelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul TEXT NOT NULL,
    file_pdf TEXT,
    content TEXT,
    teacher_id UUID REFERENCES auth.users NOT NULL,
    tanggal DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on laporan_walikelas
ALTER TABLE public.laporan_walikelas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own walikelas" ON public.laporan_walikelas 
    FOR ALL USING (auth.uid() = teacher_id);

-- E-Raport Table
CREATE TABLE IF NOT EXISTS public.eraport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES public.siswa(nis) ON DELETE CASCADE,
    nilai INTEGER NOT NULL,
    semester TEXT NOT NULL,
    mapel TEXT NOT NULL,
    teacher_id UUID REFERENCES auth.users NOT NULL,
    tugas1 INTEGER DEFAULT 0,
    tugas2 INTEGER DEFAULT 0,
    formatif1 INTEGER DEFAULT 0,
    formatif2 INTEGER DEFAULT 0,
    pts INTEGER DEFAULT 0,
    uas INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on eraport
ALTER TABLE public.eraport ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own eraport" ON public.eraport 
    FOR ALL USING (auth.uid() = teacher_id);

-- KKM Table
CREATE TABLE IF NOT EXISTS public.kkm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    value INTEGER NOT NULL,
    teacher_id UUID REFERENCES auth.users NOT NULL,
    UNIQUE(subject, teacher_id)
);

-- Enable RLS on kkm
ALTER TABLE public.kkm ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own kkm" ON public.kkm 
    FOR ALL USING (auth.uid() = teacher_id);

-- Absensi Siswa Table
CREATE TABLE IF NOT EXISTS public.absensi_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT REFERENCES public.siswa(nis) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    status TEXT NOT NULL, -- Hadir, Izin, Sakit, Alpa
    teacher_id UUID REFERENCES auth.users NOT NULL,
    UNIQUE(nis, tanggal, teacher_id)
);

-- Enable RLS on absensi_siswa
ALTER TABLE public.absensi_siswa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own absensi" ON public.absensi_siswa 
    FOR ALL USING (auth.uid() = teacher_id);

-- AI Documents Table
CREATE TABLE IF NOT EXISTS public.ai_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    pdf_url TEXT,
    created_by UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on ai_documents
ALTER TABLE public.ai_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own ai_docs" ON public.ai_documents 
    FOR ALL USING (auth.uid() = created_by);

-- STORAGE SETUP
-- 1. Create the bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('EduAdmin', 'EduAdmin', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Storage Policies
-- Allow public read access to EduAdmin bucket
CREATE POLICY "Public Access" ON storage.objects 
    FOR SELECT USING (bucket_id = 'EduAdmin');

-- Allow authenticated users to upload to their own folder
-- Path format: folder/uid/filename
CREATE POLICY "Authenticated Uploads" ON storage.objects 
    FOR INSERT WITH CHECK (
        bucket_id = 'EduAdmin' AND 
        auth.role() = 'authenticated' AND
        (storage.foldername(name))[2] = auth.uid()::text
    );

-- Allow users to update/delete their own uploads
CREATE POLICY "Owner Updates" ON storage.objects 
    FOR UPDATE USING (
        bucket_id = 'EduAdmin' AND 
        (storage.foldername(name))[2] = auth.uid()::text
    );

CREATE POLICY "Owner Deletes" ON storage.objects 
    FOR DELETE USING (
        bucket_id = 'EduAdmin' AND 
        (storage.foldername(name))[2] = auth.uid()::text
    );

